<div class="gigacalculator" data-tool="/calculators/productivity-calculator.php" data-width="450">
  <div class="gigacalctitle">Productivity Calculator</div>
  <div class="gigacalcfooter">
    <a href="https://www.gigacalculator.com/calculators/productivity-calculator.php">Productivity Calculator</a> by <a class="gigacalclink" href="https://www.gigacalculator.com/">GIGAcalculator.com</a>
  </div>

theme: jekyll-theme-midnight